/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab56;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private DefaultTableModel defaultTableModel;
    List<Tivi> listTivi = new ArrayList<>();
    ButtonGroup buttonGroup = new ButtonGroup();

    public Main() {
        initComponents();
        rdConKhaNang();
    }

    public void rdConKhaNang() {
        buttonGroup.add(rdCo);
        buttonGroup.add(rdKhong);
    }

    public void show_Tivi() {
        List<Tivi> list = new ArrayList<>();
        defaultTableModel = (DefaultTableModel) tbTivi.getModel();
        Object[] row = new Object[10];
        for (int i = 0; i < listTivi.size(); i++) {
            row[0] = list.get(i).getMa();
            row[1] = list.get(i).getTen();
            row[2] = list.get(i).getMoTa();
            row[3] = list.get(i).getNgaySanXuat();
            row[4] = list.get(i).getLoai();
            row[5] = list.get(i).getInch();
            row[6] = list.get(i).getKhaNang();
            row[7] = list.get(i).getConKhaDung();
            row[8] = list.get(i).getDoPhanGiai();
            defaultTableModel.addRow(row);
        }
    }

    public void update() {
        try {
            Connection connection = DBContext.getConnection();
//        int row = tbTivi.getSelectedRow();
//        String value = (tbTivi.getModel().getValueAt(row, 0).toString());
            String sql = "UPDATE TIVI SET TEN=?, MOTA=?, NGAYSANXUAT=?, LOAI=?, INCH=?, KHANANG=?, CONKHADUNG=?, DOPHANGIAI=? WHERE MA=?";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);

            preparedStatement.setString(9, txtMa.getText());
            preparedStatement.setString(1, txtTen.getText());
            preparedStatement.setString(2, txtMoTa.getText());

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(dcNgaySanXuat.getDate());
            preparedStatement.setString(3, date);

            preparedStatement.setString(4, cbLoai.getSelectedItem().toString());

            preparedStatement.setString(5, txtInch.getText());

            String khaNang = "";
            if (ckChongLoa.isSelected()) {
                khaNang += ckChongLoa.getText() + " ";
            }
            if (ckKetNoiNhanh.isSelected()) {
                khaNang += ckKetNoiNhanh.getText() + " ";
            }
            preparedStatement.setString(6, khaNang);

            if (rdCo.isSelected()) {
                preparedStatement.setString(7, "có ips");
            }
            if (rdKhong.isSelected()) {
                preparedStatement.setString(7, "không ips");
            }

            preparedStatement.setString(8, cbDoPhanGiai.getSelectedItem().toString());

            preparedStatement.executeUpdate();
            defaultTableModel = (DefaultTableModel) tbTivi.getModel();
            defaultTableModel.setRowCount(0);
            show_Tivi();
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        } catch (SQLException ex) {
            System.out.println("lỗi" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMa = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        lblTen = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lblMoTa = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        lblNgaySanXuat = new javax.swing.JLabel();
        dcNgaySanXuat = new com.toedter.calendar.JDateChooser();
        cbLoai = new javax.swing.JComboBox<>();
        lblLoai = new javax.swing.JLabel();
        lblInch = new javax.swing.JLabel();
        txtInch = new javax.swing.JTextField();
        lblKhaNang = new javax.swing.JLabel();
        ckChongLoa = new javax.swing.JCheckBox();
        ckKetNoiNhanh = new javax.swing.JCheckBox();
        lblConKhaDung = new javax.swing.JLabel();
        rdCo = new javax.swing.JRadioButton();
        rdKhong = new javax.swing.JRadioButton();
        lblDoPhanGiai = new javax.swing.JLabel();
        cbDoPhanGiai = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTivi = new javax.swing.JTable();
        btnHienThi = new javax.swing.JButton();
        btnLoc = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMa.setText("Mã");

        lblTen.setText("Tên");

        lblMoTa.setText("Mô tả");

        lblNgaySanXuat.setText("Ngày Sản Xuất");

        cbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "có ips", "không ips" }));

        lblLoai.setText("Loại");

        lblInch.setText("Inch");

        lblKhaNang.setText("Khả Năng");

        ckChongLoa.setText("chống lóa");

        ckKetNoiNhanh.setText("kết nối nhanh");

        lblConKhaDung.setText("Còn khả dụng");

        rdCo.setText("Có");

        rdKhong.setText("Không");

        lblDoPhanGiai.setText("Độ phân giải");

        cbDoPhanGiai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FULL HD", "4K", "2K", "HD" }));

        tbTivi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Mô tả", "Ngày sản xuất", "Loại", "Inch", "Khả năng", "Còn khả dụng", "Độ phân giải"
            }
        ));
        tbTivi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTiviMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTivi);

        btnHienThi.setText("Hiển thị");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNgaySanXuat)
                                    .addComponent(lblLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblInch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblKhaNang)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblDoPhanGiai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblConKhaDung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbDoPhanGiai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ckChongLoa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(ckKetNoiNhanh))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdCo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdKhong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dcNgaySanXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addComponent(txtInch)))))
                        .addGap(264, 264, 264)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLoc)
                            .addComponent(btnHienThi)
                            .addComponent(btnThem))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSua)
                            .addComponent(btnXoa)
                            .addComponent(btnThoat))
                        .addContainerGap(237, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMa)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTen)
                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnHienThi)
                                    .addComponent(btnSua))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMoTa)
                                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnLoc)
                                    .addComponent(btnXoa))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNgaySanXuat)
                            .addComponent(dcNgaySanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnThoat))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoai)
                    .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInch)
                    .addComponent(txtInch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKhaNang)
                    .addComponent(ckChongLoa)
                    .addComponent(ckKetNoiNhanh))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConKhaDung)
                    .addComponent(rdCo)
                    .addComponent(rdKhong))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoPhanGiai)
                    .addComponent(cbDoPhanGiai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTiviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTiviMouseClicked
        // TODO add your handling code here:
        int row = tbTivi.getSelectedRow();
        defaultTableModel = (DefaultTableModel) tbTivi.getModel();
        txtMa.setText(tbTivi.getValueAt(row, 0).toString());
        txtTen.setText(tbTivi.getValueAt(row, 1).toString());
        txtMoTa.setText(tbTivi.getValueAt(row, 2).toString());
        try {
            Date date = new SimpleDateFormat("dd-MM-yyyy").parse((String) defaultTableModel.getValueAt(row, 3));
            dcNgaySanXuat.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbLoai.setSelectedItem(tbTivi.getValueAt(row, 4));
        txtInch.setText(tbTivi.getValueAt(row, 5).toString());
        String check = defaultTableModel.getValueAt(row, 6).toString();
        switch (check) {
            case "chong loa":
                ckChongLoa.setSelected(true);
                ckKetNoiNhanh.setSelected(false);
                break;
            case "ket noi nhanh":
                ckKetNoiNhanh.setSelected(true);
                ckChongLoa.setSelected(false);
                break;
            default:
                ckChongLoa.setSelected(true);
                ckKetNoiNhanh.setSelected(true);
                break;
        }
        String conKhaDung = defaultTableModel.getValueAt(row, 7).toString();
        if (conKhaDung.equals("có")) {
            rdCo.setSelected(true);
        } else if (conKhaDung.equals("không")) {
            rdKhong.setSelected(true);
        }
        cbDoPhanGiai.setSelectedItem(tbTivi.getValueAt(row, 8));
    }//GEN-LAST:event_tbTiviMouseClicked

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        // TODO add your handling code here:
        try {
            String query = "SELECT MA, TEN, MOTA, NGAYSANXUAT, LOAI, INCH, KHANANG, CONKHADUNG, DOPHANGIAI FROM TIVI";

            Connection connection = DBContext.getConnection();
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            ResultSet rs = preparedStatement.executeQuery();
            while (rs.next()) {
                String ma = rs.getString("Ma");
                String ten = rs.getString("TEN");
                String moTa = rs.getString("MOTA");
                String ngaySanXuat = rs.getString("NGAYSANXUAT");
                String loai = rs.getString("LOAI");
                String inch = String.valueOf(rs.getInt("INCH"));
                String khaNang = rs.getString("KHANANG");
                String conKhaDung = rs.getString("CONKHADUNG");
                String doPhanGiai = rs.getString("DOPHANGIAI");

                String[] data = {ma, ten, moTa, ngaySanXuat, loai, inch, khaNang, conKhaDung, doPhanGiai};
                defaultTableModel = (DefaultTableModel) tbTivi.getModel();
                defaultTableModel.addRow(data);

            }
        } catch (SQLException ex) {
            System.out.println("Lỗi :" + ex.getMessage());
        }
    }//GEN-LAST:event_btnHienThiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // TODO add your handling code here:
            Connection connection = DBContext.getConnection();
            Object sql = "INSERT INTO TIVI (MA, TEN, MOTA, NGAYSANXUAT, LOAI, INCH, KHANANG, CONKHADUNG, DOPHANGIAI) VALUES (?,?,?,?,?,?,?,?,?)";
            PreparedStatement preparedStatement = connection.prepareStatement((String) sql);
            preparedStatement.setString(1, txtMa.getText());
            preparedStatement.setString(2, txtTen.getText());
            preparedStatement.setString(3, txtMoTa.getText());
            String conKhaDung = null;
            if (rdCo.isSelected()) {
                conKhaDung = "có";
            }
            if (rdKhong.isSelected()) {
                conKhaDung = "không";
            }
            preparedStatement.setString(8, conKhaDung);
            String khaNang = "";
            if (ckChongLoa.isSelected()) {
                khaNang += ckChongLoa.getText() + " ";
            }
            if (ckKetNoiNhanh.isSelected()) {
                khaNang += ckKetNoiNhanh.getText() + " ";
            }
            preparedStatement.setString(7, khaNang);
            String loai;
            loai = cbLoai.getSelectedItem().toString();
            preparedStatement.setString(5, loai);
            String doPhanGiai;
            doPhanGiai = cbDoPhanGiai.getSelectedItem().toString();
            preparedStatement.setString(9, doPhanGiai);
            preparedStatement.setString(6, txtInch.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String date = sdf.format(dcNgaySanXuat.getDate());
            preparedStatement.setString(4, date);
            preparedStatement.executeUpdate();
            defaultTableModel.setRowCount(0);
            show_Tivi();
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            // TODO add your handling code here:
            Connection connection = DBContext.getConnection();
            String query = "DELETE FROM TIVI WHERE (MA=?)";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, txtMa.getText());
            pst.executeUpdate();
            defaultTableModel.setRowCount(0);
            show_Tivi();
            JOptionPane.showMessageDialog(this, "Xóa thành công.");
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:
        try {
            String query = "SELECT MA, TEN, MOTA, NGAYSANXUAT, LOAI, INCH, KHANANG, CONKHADUNG, DOPHANGIAI FROM TIVI WHERE CONKHADUNG='có'";

            Connection connection = DBContext.getConnection();
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            ResultSet rs = preparedStatement.executeQuery();
            while (rs.next()) {
                String ma = rs.getString("Ma");
                String ten = rs.getString("TEN");
                String moTa = rs.getString("MOTA");
                String ngaySanXuat = rs.getString("NGAYSANXUAT");
                String loai = rs.getString("LOAI");
                String inch = String.valueOf(rs.getInt("INCH"));
                String khaNang = rs.getString("KHANANG");
                String conKhaDung = rs.getString("CONKHADUNG");
                String doPhanGiai = rs.getString("DOPHANGIAI");

                String[] data = {ma, ten, moTa, ngaySanXuat, loai, inch, khaNang, conKhaDung, doPhanGiai};
                defaultTableModel = (DefaultTableModel) tbTivi.getModel();
                defaultTableModel.addRow(data);

            }
        } catch (SQLException ex) {
            System.out.println("Lỗi :" + ex.getMessage());
        }
    }//GEN-LAST:event_btnLocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbDoPhanGiai;
    private javax.swing.JComboBox<String> cbLoai;
    private javax.swing.JCheckBox ckChongLoa;
    private javax.swing.JCheckBox ckKetNoiNhanh;
    private com.toedter.calendar.JDateChooser dcNgaySanXuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConKhaDung;
    private javax.swing.JLabel lblDoPhanGiai;
    private javax.swing.JLabel lblInch;
    private javax.swing.JLabel lblKhaNang;
    private javax.swing.JLabel lblLoai;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblNgaySanXuat;
    private javax.swing.JLabel lblTen;
    private javax.swing.JRadioButton rdCo;
    private javax.swing.JRadioButton rdKhong;
    private javax.swing.JTable tbTivi;
    private javax.swing.JTextField txtInch;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
